name: teknopark_pdks
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  connectivity_plus: ^5.0.2
  flutter_easyloading: ^3.0.5
  back_button_interceptor: ^7.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  intl: ^0.18.1
  lottie: ^2.3.2
  package_info: ^2.0.2
  image_picker: ^1.0.6
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottieFiles/